receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024

  resource/plugin_versions:
    attributes:
      - key: symbiosis.as_you.version
        value: ${env:AS_YOU_VERSION}
        action: upsert
      - key: symbiosis.with_me.version
        value: ${env:WITH_ME_VERSION}
        action: upsert

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [100, 500, 1000, 5000, 10000, 50000, 100000]
    dimensions:
      - name: model
      - name: symbiosis.as_you.version
      - name: symbiosis.with_me.version
    dimensions_cache_size: 1000
    metrics_flush_interval: 15s

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    resource_to_telemetry_conversion:
      enabled: true
    metric_expiration: 5m

  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource/plugin_versions]
      exporters: [spanmetrics, debug]

    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch, resource/plugin_versions]
      exporters: [prometheus, debug]

    logs:
      receivers: [otlp]
      processors: [batch, resource/plugin_versions]
      exporters: [debug]
